apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application3
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/git4nishant/argocd-app-config.git
    targetRevision: HEAD
    path: qa
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp3

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
