apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application2
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/git4nishant/argocd-app-config.git
    targetRevision: HEAD
    path: production
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp-2

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
